# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-24 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buying',
            name='cost',
            field=models.FloatField(default=1, verbose_name='Price for Buy'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(default=0, verbose_name='Price'),
        ),
    ]
