# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20180924_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buying',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Items_Buy', to='mainapp.Item'),
        ),
    ]
