# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20180925_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buying',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Item'),
        ),
    ]
