# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 03:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20180926_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stock',
            field=models.IntegerField(default=1, verbose_name='Stock'),
        ),
        migrations.AddField(
            model_name='item',
            name='stock_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
