# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20180926_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_sell',
            field=models.BooleanField(default=True),
        ),
    ]
