# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 03:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_item_is_sell'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyingOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Vender')),
            ],
        ),
        migrations.RemoveField(
            model_name='buying',
            name='date',
        ),
        migrations.AddField(
            model_name='buyingorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Vendor'),
        ),
        migrations.AddField(
            model_name='buying',
            name='buying_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.BuyingOrder'),
            preserve_default=False,
        ),
    ]
