# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-29 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20180927_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyingorder',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='item',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock'),
        ),
    ]
