# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-01 04:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20180929_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 10, 1, 4, 29, 26, 57668, tzinfo=utc))),
                ('amount', models.IntegerField(default=0, verbose_name='Money')),
            ],
        ),
        migrations.CreateModel(
            name='Selling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2018, 10, 1, 4, 29, 26, 58666, tzinfo=utc))),
                ('time', models.TimeField(default=datetime.datetime(2018, 10, 1, 4, 29, 26, 58666, tzinfo=utc))),
                ('price', models.FloatField(default=1)),
                ('cost', models.FloatField(default=1)),
                ('qty', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Item')),
            ],
        ),
    ]
