# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-01 04:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_cashier_selling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashier',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='selling',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='selling',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
