# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-02 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20181001_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='selling',
            name='item_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
