# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-08 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_selling_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selling',
            name='item_name',
        ),
    ]
